name: URL_launcher
description: A simple application to save and launch URLs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher:
  hive:
  hive_flutter:
  path_provider:
  flutter_staggered_animations:
  animations:
  flutter_slidable:
  provider:
  quick_actions:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  image_path: "assets/app-icon.png"
  android: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/app-icon.png"
  android: true

flutter:
  uses-material-design: true